APP:
  ERROR:
    DONE: command done
    FILES: files
    UNEXPECTED_TYPE: >-
      Not expecting *`REPLACE`* in this step\. Maybe something went wrong?? Anyway
      send /start to restart the process
  HELP:
    MESSAGE: |-
      When you send /start the process will begin\.

      You can always send /start to reset the process to the beginning\.

      *1\.* *send the background* of your post \(square crop of AOE screenshot\)

      *2\.* *send the unedited photos* of your shirt\.
      You may send multiple pictures of the same shirt\.

      *3\.* Confirm your choice by sending the command /done\.

      From now on, the bot will take over and process your images\. It will crop
      out the shirts and place them on your background image and send the
      results as files

      Send /start to begin\.
  RECIEVE_SHIRT:
    DONE: 'Received shirts, now processing\.\.\.'
    INIT: 'Send unedited shirt photos, after all the shirts were added send /done'
    ON_DOCUMENT: Shirt received
  RETURN_RESULT:
    INIT: |-
      Done
      Send /start if you want to process more shirts
  SETTING_BACKGROUND:
    INIT: |-
      Welcome to the AOE Shirtbot\! send /help for help\.
      Send the background Image of your post
COMMANDS:
  DONE: done
  HELP: help
  START: start
SYNTAX:
  PLACEHOLDER: REPLACE